#- ASPNETCORE_ENVIRONMENT=Development


version: '3.4'



####### Networks #######

networks:
  networkPortal:

####### Services #######

services:
#-----------------------------------------------------------------------
  MsSqLServer2019:
    container_name: MsSqLServer2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Aa@123456
      - ACCEPT_EULA=Y
    ports:
      - 51433:1433
    networks:
     - networkPortal
#-----------------------------------------------------------------------
  shj.commerce.web.api:
    container_name: "ShjCommerceApi"
    image: ${DOCKER_REGISTRY-}shjcommercewebapi
    build:
      context: .
      dockerfile: src/SHJ.Commerce.Web.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - MsSqLServer2019
    ports:
      - 58080:8080
    networks:
     - networkPortal
#-----------------------------------------------------------------------
  shj.commerce.authserver.web.mvc:
    image: ${DOCKER_REGISTRY-}shjcommerceauthserverwebmvc
    build:
      context: .
      dockerfile: src/SHJ.Commerce.AuthServer.Web.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - MsSqLServer2019
    ports:
      - 58081:8080
    networks:
     - networkPortal
#-----------------------------------------------------------------------

  shj.commerce.dashboard.web.mvc:
    image: ${DOCKER_REGISTRY-}shjcommercedashboardwebmvc
    build:
      context: .
      dockerfile: src/SHJ.Commerce.Dashboard.Web.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - MsSqLServer2019
    ports:
      - 58082:8080
    networks:
     - networkPortal

#-----------------------------------------------------------------------